### ISSUE TITLE
Do we need to credit a different monitoring service?

### ISSUE THREAD

**Issue by tomjaguarpaw** [haskell-infra/haskell-admins#1]
As per https://github.com/haskell-infra/www.haskell.org/pull/85 the site webmon.com does not seem to exist. I have removed the reference to that site from `master`. However, if we still have monitoring we should properly credit the service that is offering it to us. Is it still webmon? Do they have have a different/name site?

**Comment by gbaz** [comment]
we use uptimerobot now, but we're not getting a donation of a high quality plan from them, so we're on the universal free tier, no need to credit.
