### ISSUE TITLE
Please redirect `[www.]haskell.org/haddock/*` to readthedocs

### ISSUE THREAD

**Issue by tomjaguarpaw** [haskell-infra/haskell-admins#7]
On behalf of the Haddock maintainers [@Kleidukos requests](https://github.com/haskell/haddock/issues/1443) that the haskell.org `haddock/` subsite be redirected to the up-to-date source of documentation, that is https://haskell-haddock.readthedocs.io/

Would you mind doing so with a redirect rule in the webserver? Alternatively I can make an HTML file with an HTTP-equiv redirect for each file in the old subsite, but the former seems like a cleaner approach.

**Comment by gbaz** [comment]
done.

**Comment by tomjaguarpaw** [comment]
Thank you for a swift turnaround!
