### ISSUE TITLE
status.haskell.org doesn't list matrix.hackage.haskell.org

### ISSUE THREAD

**Issue by phlummox** [haskell-infra/haskell-admins#9]
Currently, the [matrix.hackage.haskell](https://matrix.hackage.haskell.org) site seems not to be working: e.g. the status "badges" it's serving up are giving 500 status and an error message. (For example - `curl https://matrix.hackage.haskell.org/api/v2/packages/vector/badge` gives an error.)

I reported the matrix.hackage.haskell issues [here][hackage-issue], but another issue is that despite the outage for that site,

- https://status.haskell.org reports that Hackage is "Operational" (which I guess is mostly true, but could be more informative)
- https://status.haskell.org  seems to have a broken-ish link to http://auto-status.haskell.org/ - the  http://auto-status.haskell.org/ site itself is up (and gives 200 HTTP statuses), but certainly doesn't seem to be reporting on the health of haskell.org services properly (currently it's saying there's some sort of 404 error happening).

[hackage-issue]: https://github.com/haskell/hackage-server/issues/997

Could the status of matrix.hackage.haskell be added to the status.haskell.org page? And does the link to http://auto-status.haskell.org/ need to be updated?

**Comment by phlummox** [comment]
Also, the broken-ish auto-status link seems to be included in the [README](https://github.com/haskell-infra/haskell-admins/blob/5445e15424e53fa07e7052a966a3a176b888dc27/README.md#the-team-and-how-to-contact-them), so the link there probably needs to be updated too.

**Comment by gbaz** [comment]
auto-status is now fixed.

**Comment by gbaz** [comment]
candidate replacement (not an improvement, just getting everything working again on a new box) at https://matrix.haskell.org -- we plan to swap it over soon, if anyone wants to poke it a bit first and see if they're comfortable with it.

**Comment by tomjaguarpaw** [comment]
Cool, thanks! A quick check didn't turn up any problems. Builds for later GHCs seem to be missing, but perhaps that's expected as the dataset is rebuilt?

**Comment by andreasabel** [comment]
Close this as the matrix is gone for good now?

**Comment by gbaz** [comment]
yeah, sadly.
